name: Rust

on:
  push:
    branches: [ "main", "v[0-9]+.[0-9]+.[0-9]+*" ]
  pull_request:
    branches: [ "main", "v[0-9]+.[0-9]+.[0-9]+*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu

    - name: install dependencies (ubuntu only)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Run tests for crate
      run: |
        cd tauri-interop-macro
        cargo test --features event,leptos,initial_value

    - name: Run tests for crate
      run: cargo test --all-features

    - name: Build test-project (wasm)
      run: |
        cd test-project
        cargo build --target wasm32-unknown-unknown

    - name: Build test-project (host)
      run: |
        cd test-project/api
        cargo build --target x86_64-unknown-linux-gnu
